# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.csv_parser:
        class: AppBundle\Services\CSVParserService
        arguments: ['@service_container']
